# Generated by Django 3.1.2 on 2020-10-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_date', models.DateField()),
                ('return_date', models.DateField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HireElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.hire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.product')),
            ],
        ),
        migrations.AddField(
            model_name='hire',
            name='hirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.hirer'),
        ),
    ]
