# Generated by Django 3.1.2 on 2020-11-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20201115_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hire',
            options={'ordering': ('return_date',)},
        ),
        migrations.AlterField(
            model_name='hire',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hirer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hireelement',
            name='hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elems', to='application.hire'),
        ),
        migrations.DeleteModel(
            name='Hirer',
        ),
    ]
