# Generated by Django 3.1.2 on 2020-11-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201121_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireelement',
            name='hire',
        ),
        migrations.RemoveField(
            model_name='hireelement',
            name='product',
        ),
        migrations.DeleteModel(
            name='Hire',
        ),
        migrations.DeleteModel(
            name='HireElement',
        ),
    ]
