# Generated by Django 3.1.2 on 2020-11-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_auto_20201121_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer', models.PositiveIntegerField()),
                ('taking_date', models.DateField()),
                ('return_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ('return_date',),
            },
        ),
        migrations.CreateModel(
            name='HireElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elems', to='orders.hire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.product')),
            ],
        ),
    ]
