# Generated by Django 3.1.2 on 2020-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_hire_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='slug',
            field=models.SlugField(default='ads', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hireelement',
            name='slug',
            field=models.SlugField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
