# Generated by Django 3.1.2 on 2020-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201124_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='number',
            field=models.PositiveIntegerField(default=8),
            preserve_default=False,
        ),
    ]
